# These are supported funding model platforms
github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username Murshid69 user 2 mmjgroup 
open_collective: # merge all wallet
ko_fi: # merge all wallet
tidelift: # Tidelift platform-name/package-name e.g.,100 npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: #merge all wallet or Replace with a single Polar username
buy_me_a_coffee: #  Replace with a single Buy Me a Coffee username
: #  merge all wallet
custom: # without Replace with up to 4 custom sponsorship URLs e.g., ['link19qmTHovFDABKZFt6NYpDBePmy65v7Mz3Mn3qTD6EsAfb9qmTHovFDABKZFt6NYpDBePmy65v7Mz3Mn3qTD6EsAfb9qmTHovFDABKZFt6NYpDBePmy65v7Mz3Mn3qTD6EsAfb', 'link2']
